"""
Quarterly Tranco-list refresh helper.

Operations recipe (per OPS runbook, ~ every quarter):

    cd hardening/reality/seeds
    python update_top1k.py --output top1k.json

Reads Tranco's daily list, extracts the top 1000, writes the JSON file
this directory packages. Designed as a stand-alone script (not part of
the runtime audit pipeline) so the audit stays zero-network.

Tranco's daily list URL pattern (2026-04 stable):
    https://tranco-list.eu/top-1m.csv.zip

The script is intentionally simple — stdlib only, no aiohttp. If a
maintainer wants to plug in a different ranking source (Cisco Umbrella,
Majestic Million), the JSON schema in `top1k.json` is the contract;
just write to it.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import sys
import urllib.request
import zipfile
from datetime import UTC, datetime
from pathlib import Path

TRANCO_URL = "https://tranco-list.eu/top-1m.csv.zip"
TOP_N = 1000


def fetch_top_n(url: str = TRANCO_URL, n: int = TOP_N) -> list[dict]:
    """Download Tranco zip, extract csv, return top-N as schema entries."""
    print(f"fetching {url} ...", file=sys.stderr)
    with urllib.request.urlopen(url, timeout=60) as resp:
        zip_bytes = resp.read()
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        # Tranco zips a single csv named like 'top-1m.csv'
        names = [n for n in zf.namelist() if n.endswith(".csv")]
        if not names:
            raise SystemExit(f"no csv in {url}")
        with zf.open(names[0]) as f:
            text = io.TextIOWrapper(f, encoding="utf-8")
            reader = csv.reader(text)
            entries = []
            for row in reader:
                if len(row) < 2:
                    continue
                rank, host = row[0], row[1].strip().lower()
                try:
                    rank_i = int(rank)
                except ValueError:
                    continue
                entries.append({"host": host, "rank": rank_i})
                if len(entries) >= n:
                    break
            return entries


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default=str(Path(__file__).parent / "top1k.json"),
        help="output JSON path (default: ./top1k.json)",
    )
    parser.add_argument(
        "--source",
        default=TRANCO_URL,
        help="alternate ranking source URL (must be Tranco-format zip)",
    )
    args = parser.parse_args(argv)

    entries = fetch_top_n(url=args.source, n=TOP_N)
    payload = {
        "_comment": (
            "Auto-generated by hardening/reality/seeds/update_top1k.py. "
            "Tranco top-1k snapshot. Refresh quarterly via this script."
        ),
        "_source": args.source,
        "_schema": (
            "Each entry: {host: string, rank: int}. "
            "Rank ≤100 = critical, 101–1000 = warning, otherwise no penalty."
        ),
        "_last_refreshed": datetime.now(UTC).date().isoformat(),
        "entries": entries,
    }
    out = Path(args.output)
    out.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(entries)} entries to {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
